### ISSUE TITLE
Full dn for Starter.LDAP.user

### ISSUE THREAD

**Issue by jas01** [J-Christophe/DOI#13]
**Is your feature request related to a problem? Please describe.**

After some test I notice the user send to the ldap server is the concat of Starter.LDAP.user and  Starter.LDAP.search.user. That's is not IMHO a good choice because that's imply we need to have a "regular" user for the bind to the ldap server. 
That's mean we cannot use some non user account to bind a service. 

**Describe the solution you'd like**

I think it's more usable to just use Starter.LDAP.user to bind the ldap connection, so those who want use a user account still can and those who prefer use a non_user account can do it.

**Comment by J-Christophe** [comment]
Thanks a lot for the remark, I will fix it ASAP
