### ISSUE TITLE
Flag in config file to not use encrypted field

### ISSUE THREAD

**Issue by jas01** [J-Christophe/DOI#14]
**Is your feature request related to a problem? Please describe.**

We use a deployment software (puppet) to configure all our infrastructure. But I could use some kubnernetes or openshift or whatever automatic deployment software. So the encrypted field for the config file is very painful. And more important I really don't see the advantage, especially when the decryption process is clearly indicate inside the file....

So event I don't understand why someone would like to have encrypted config file, I can respect that, so can you add some flag on the top of the config file like

`encrypted_fields = true/false`

or if you have time 

`encrypted_fields = [ field1, field2, etc. ] or []`

**Describe the solution you'd like**
For me 
`encrypted_fields = true/false`
would be super fine.

**Comment by J-Christophe** [comment]
It is possible to give the secretkey as parameter on the command line when running the DOI-server. However, I understand your problem. So I will add the parameter Starter.encrypted_fields = true/false (by default is true) in the configuration file
